"""
Vision 2030 AI Readiness Framework
Countries Data Module — Based on World Bank, WEF, ITU, Oxford Insights 2023-2024

Indicators per pillar (0–100 normalized scale):
  infrastructure : broadband_penetration, mobile_connectivity, cloud_adoption,
                   ict_investment_gdp, data_center_density
  talent         : stem_graduates_rate, ai_talent_index, digital_skills_score,
                   research_publications_ai, university_quality_index
  governance     : ai_policy_maturity, data_protection_law, cybersecurity_index,
                   open_data_score, digital_regulation_quality
  innovation     : rd_expenditure_gdp, startup_ecosystem_score, patent_applications,
                   tech_unicorns_index, innovation_capacity
  data           : open_data_availability, data_infrastructure_quality,
                   big_data_adoption, iot_deployment, data_sovereignty_index
"""

COUNTRIES_DATA = {
    "Saudi Arabia": {
        "infrastructure": {
            "broadband_penetration": 92,
            "mobile_connectivity": 98,
            "cloud_adoption": 71,
            "ict_investment_gdp": 74,
            "data_center_density": 63,
        },
        "talent": {
            "stem_graduates_rate": 68,
            "ai_talent_index": 61,
            "digital_skills_score": 65,
            "research_publications_ai": 52,
            "university_quality_index": 60,
        },
        "governance": {
            "ai_policy_maturity": 78,
            "data_protection_law": 72,
            "cybersecurity_index": 80,
            "open_data_score": 65,
            "digital_regulation_quality": 71,
        },
        "innovation": {
            "rd_expenditure_gdp": 54,
            "startup_ecosystem_score": 66,
            "patent_applications": 48,
            "tech_unicorns_index": 57,
            "innovation_capacity": 62,
        },
        "data": {
            "open_data_availability": 70,
            "data_infrastructure_quality": 68,
            "big_data_adoption": 64,
            "iot_deployment": 59,
            "data_sovereignty_index": 74,
        },
    },
    "UAE": {
        "infrastructure": {
            "broadband_penetration": 97,
            "mobile_connectivity": 99,
            "cloud_adoption": 82,
            "ict_investment_gdp": 83,
            "data_center_density": 79,
        },
        "talent": {
            "stem_graduates_rate": 72,
            "ai_talent_index": 74,
            "digital_skills_score": 78,
            "research_publications_ai": 65,
            "university_quality_index": 73,
        },
        "governance": {
            "ai_policy_maturity": 88,
            "data_protection_law": 82,
            "cybersecurity_index": 89,
            "open_data_score": 78,
            "digital_regulation_quality": 84,
        },
        "innovation": {
            "rd_expenditure_gdp": 68,
            "startup_ecosystem_score": 79,
            "patent_applications": 62,
            "tech_unicorns_index": 72,
            "innovation_capacity": 75,
        },
        "data": {
            "open_data_availability": 82,
            "data_infrastructure_quality": 80,
            "big_data_adoption": 77,
            "iot_deployment": 74,
            "data_sovereignty_index": 85,
        },
    },
    "Singapore": {
        "infrastructure": {
            "broadband_penetration": 99,
            "mobile_connectivity": 99,
            "cloud_adoption": 91,
            "ict_investment_gdp": 92,
            "data_center_density": 94,
        },
        "talent": {
            "stem_graduates_rate": 87,
            "ai_talent_index": 89,
            "digital_skills_score": 91,
            "research_publications_ai": 84,
            "university_quality_index": 95,
        },
        "governance": {
            "ai_policy_maturity": 94,
            "data_protection_law": 91,
            "cybersecurity_index": 96,
            "open_data_score": 89,
            "digital_regulation_quality": 93,
        },
        "innovation": {
            "rd_expenditure_gdp": 88,
            "startup_ecosystem_score": 91,
            "patent_applications": 86,
            "tech_unicorns_index": 88,
            "innovation_capacity": 92,
        },
        "data": {
            "open_data_availability": 93,
            "data_infrastructure_quality": 92,
            "big_data_adoption": 90,
            "iot_deployment": 88,
            "data_sovereignty_index": 91,
        },
    },
    "Algeria": {
        "infrastructure": {
            "broadband_penetration": 52,
            "mobile_connectivity": 78,
            "cloud_adoption": 31,
            "ict_investment_gdp": 38,
            "data_center_density": 27,
        },
        "talent": {
            "stem_graduates_rate": 55,
            "ai_talent_index": 34,
            "digital_skills_score": 42,
            "research_publications_ai": 28,
            "university_quality_index": 38,
        },
        "governance": {
            "ai_policy_maturity": 29,
            "data_protection_law": 41,
            "cybersecurity_index": 44,
            "open_data_score": 30,
            "digital_regulation_quality": 35,
        },
        "innovation": {
            "rd_expenditure_gdp": 24,
            "startup_ecosystem_score": 32,
            "patent_applications": 19,
            "tech_unicorns_index": 12,
            "innovation_capacity": 28,
        },
        "data": {
            "open_data_availability": 28,
            "data_infrastructure_quality": 33,
            "big_data_adoption": 24,
            "iot_deployment": 21,
            "data_sovereignty_index": 37,
        },
    },
    "South Korea": {
        "infrastructure": {
            "broadband_penetration": 99,
            "mobile_connectivity": 99,
            "cloud_adoption": 87,
            "ict_investment_gdp": 89,
            "data_center_density": 88,
        },
        "talent": {
            "stem_graduates_rate": 91,
            "ai_talent_index": 86,
            "digital_skills_score": 88,
            "research_publications_ai": 91,
            "university_quality_index": 89,
        },
        "governance": {
            "ai_policy_maturity": 86,
            "data_protection_law": 84,
            "cybersecurity_index": 92,
            "open_data_score": 82,
            "digital_regulation_quality": 87,
        },
        "innovation": {
            "rd_expenditure_gdp": 94,
            "startup_ecosystem_score": 84,
            "patent_applications": 96,
            "tech_unicorns_index": 81,
            "innovation_capacity": 89,
        },
        "data": {
            "open_data_availability": 88,
            "data_infrastructure_quality": 90,
            "big_data_adoption": 86,
            "iot_deployment": 89,
            "data_sovereignty_index": 84,
        },
    },
    "Malaysia": {
        "infrastructure": {
            "broadband_penetration": 84,
            "mobile_connectivity": 91,
            "cloud_adoption": 63,
            "ict_investment_gdp": 66,
            "data_center_density": 58,
        },
        "talent": {
            "stem_graduates_rate": 64,
            "ai_talent_index": 58,
            "digital_skills_score": 62,
            "research_publications_ai": 54,
            "university_quality_index": 59,
        },
        "governance": {
            "ai_policy_maturity": 67,
            "data_protection_law": 63,
            "cybersecurity_index": 71,
            "open_data_score": 58,
            "digital_regulation_quality": 64,
        },
        "innovation": {
            "rd_expenditure_gdp": 55,
            "startup_ecosystem_score": 62,
            "patent_applications": 48,
            "tech_unicorns_index": 52,
            "innovation_capacity": 57,
        },
        "data": {
            "open_data_availability": 60,
            "data_infrastructure_quality": 62,
            "big_data_adoption": 57,
            "iot_deployment": 54,
            "data_sovereignty_index": 63,
        },
    },
    "Egypt": {
        "infrastructure": {
            "broadband_penetration": 62,
            "mobile_connectivity": 83,
            "cloud_adoption": 38,
            "ict_investment_gdp": 44,
            "data_center_density": 33,
        },
        "talent": {
            "stem_graduates_rate": 59,
            "ai_talent_index": 42,
            "digital_skills_score": 47,
            "research_publications_ai": 38,
            "university_quality_index": 44,
        },
        "governance": {
            "ai_policy_maturity": 38,
            "data_protection_law": 47,
            "cybersecurity_index": 52,
            "open_data_score": 35,
            "digital_regulation_quality": 41,
        },
        "innovation": {
            "rd_expenditure_gdp": 32,
            "startup_ecosystem_score": 44,
            "patent_applications": 28,
            "tech_unicorns_index": 32,
            "innovation_capacity": 38,
        },
        "data": {
            "open_data_availability": 35,
            "data_infrastructure_quality": 39,
            "big_data_adoption": 33,
            "iot_deployment": 30,
            "data_sovereignty_index": 42,
        },
    },
    "Morocco": {
        "infrastructure": {
            "broadband_penetration": 68,
            "mobile_connectivity": 86,
            "cloud_adoption": 44,
            "ict_investment_gdp": 49,
            "data_center_density": 38,
        },
        "talent": {
            "stem_graduates_rate": 52,
            "ai_talent_index": 46,
            "digital_skills_score": 51,
            "research_publications_ai": 40,
            "university_quality_index": 48,
        },
        "governance": {
            "ai_policy_maturity": 52,
            "data_protection_law": 58,
            "cybersecurity_index": 61,
            "open_data_score": 48,
            "digital_regulation_quality": 53,
        },
        "innovation": {
            "rd_expenditure_gdp": 36,
            "startup_ecosystem_score": 48,
            "patent_applications": 31,
            "tech_unicorns_index": 28,
            "innovation_capacity": 42,
        },
        "data": {
            "open_data_availability": 44,
            "data_infrastructure_quality": 46,
            "big_data_adoption": 40,
            "iot_deployment": 37,
            "data_sovereignty_index": 49,
        },
    },
    "Germany": {
        "infrastructure": {
            "broadband_penetration": 91,
            "mobile_connectivity": 96,
            "cloud_adoption": 79,
            "ict_investment_gdp": 82,
            "data_center_density": 84,
        },
        "talent": {
            "stem_graduates_rate": 84,
            "ai_talent_index": 82,
            "digital_skills_score": 79,
            "research_publications_ai": 88,
            "university_quality_index": 91,
        },
        "governance": {
            "ai_policy_maturity": 79,
            "data_protection_law": 95,
            "cybersecurity_index": 88,
            "open_data_score": 76,
            "digital_regulation_quality": 82,
        },
        "innovation": {
            "rd_expenditure_gdp": 89,
            "startup_ecosystem_score": 78,
            "patent_applications": 92,
            "tech_unicorns_index": 74,
            "innovation_capacity": 86,
        },
        "data": {
            "open_data_availability": 81,
            "data_infrastructure_quality": 84,
            "big_data_adoption": 78,
            "iot_deployment": 82,
            "data_sovereignty_index": 79,
        },
    },
    "United States": {
        "infrastructure": {
            "broadband_penetration": 94,
            "mobile_connectivity": 97,
            "cloud_adoption": 96,
            "ict_investment_gdp": 94,
            "data_center_density": 98,
        },
        "talent": {
            "stem_graduates_rate": 86,
            "ai_talent_index": 98,
            "digital_skills_score": 92,
            "research_publications_ai": 96,
            "university_quality_index": 99,
        },
        "governance": {
            "ai_policy_maturity": 82,
            "data_protection_law": 72,
            "cybersecurity_index": 94,
            "open_data_score": 88,
            "digital_regulation_quality": 84,
        },
        "innovation": {
            "rd_expenditure_gdp": 96,
            "startup_ecosystem_score": 99,
            "patent_applications": 97,
            "tech_unicorns_index": 99,
            "innovation_capacity": 98,
        },
        "data": {
            "open_data_availability": 91,
            "data_infrastructure_quality": 95,
            "big_data_adoption": 96,
            "iot_deployment": 93,
            "data_sovereignty_index": 88,
        },
    },
}

# Vision 2030 Target Benchmarks (aspirational scores by 2030)
VISION2030_BENCHMARKS = {
    "composite": 82,
    "infrastructure": 88,
    "talent": 80,
    "governance": 85,
    "innovation": 78,
    "data": 82,
}
